# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21d52d2b75d6d61c0e98a4aec6e10372c02c21aff73fae2d4fad06e10e3a62022157603433c401141fecbd53b38f7b7d30fdc27ea622b8043089257b3e8a782c

test:
  secret_key_base: eaf08c0d5fae5389c64b5eebff2b417b2c42c35856ff7aa1273d66b454e5b3844e2c36315adbf2f01ed619545e138779fff000ee3195c074d7cb37b9ed7c09e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
